# Generated by Django 5.0.7 on 2024-08-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdwaitappContact',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('map', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adwaitapp_contact',
                'managed': False,
            },
        ),
    ]
