# Generated by Django 5.0.7 on 2024-08-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitsol', '0002_adwaitappmainservices_adwaitappsubservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdwaitappInquiries',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'adwaitapp_inquiries',
                'managed': False,
            },
        ),
    ]
