# Generated by Django 5.0.7 on 2024-09-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitsol', '0004_adwaitappblogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdwaitappTechnologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'adwaitapp_technologies',
                'managed': False,
            },
        ),
    ]
