# Generated by Django 5.0.7 on 2024-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitsol', '0005_adwaitapptechnologies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdwaitappTechnologiesMainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'adwaitapp_technologies_main_service',
                'managed': False,
            },
        ),
    ]
