# Generated by Django 5.0.7 on 2024-10-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adwaitsol', '0006_adwaitapptechnologiesmainservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdwaitappNewsletterSubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('subscribed_on', models.DateTimeField()),
            ],
            options={
                'db_table': 'adwaitapp_newslettersubscribe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdwaitappTechnologiesService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'adwaitapp_technologies_service',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AdwaitappTechnologiesMainService',
        ),
    ]
